### ISSUE TITLE
两个特写必须搭配BESC吗？

### ISSUE THREAD

**Issue by HSSkyBoy** [sakarie9/DOL-CHS-MODS#10]
看到BJ特寫和KR特寫出現時必含BESC，想問一下，這兩個特寫是必須搭配還是怎麽樣？

**Comment by HSSkyBoy** [comment]
可惜BESC的那個嘴巴不太好看，而且我的頭發好像太長，導致它顯示只能舍棄掉這幾個很不錯的模組了QQ

**Comment by sakarie9** [comment]
自己改吧（

现在大概八成的mod都依赖这个besc所以基本没法不装
