### ISSUE TITLE
遊戲設置的部分調整會取消成就

### ISSUE THREAD

**Issue by s96hn** [sakarie9/DOL-CHS-MODS#11]
有辦法將遊戲設置內的某些調整會取消成就的設定移除嗎
例如遇敵機率跟貝利的租金調到低於1.0就會取消成就獲得

**Comment by sakarie9** [comment]
理论上可以但我不知道要改哪（

**Comment by s96hn** [comment]
好吧 感謝回答

**Comment by s96hn** [comment]
hmmmm 自己測試了一下
html裡面的
86472行
221122行
分別有段
	&lt;&lt;if $cheatdisable is &quot;f&quot; or $rentmod lt 1&gt;&gt;
		&lt;&lt;set $feats.locked to true&gt;&gt;
直接把1改成0.1就OK了
設定的時候還是會跳警告 但我自己測試是能正常獲得成就 我技術力不夠不知道怎麼去掉警告
租金的部分是這樣 遇敵機率還要找一下

**Comment by sakarie9** [comment]
重做了作弊功能，现在应该不会锁成就了

**Comment by HSSkyBoy** [comment]
woqu
原来作弊mod是您做的
