### ISSUE TITLE
请求在下次更新中加入AP显示模组

### ISSUE THREAD

**Issue by Benotasheep** [sakarie9/DOL-CHS-MODS#13]
如题，有显示HP血量数值的模组，希望能够添加显示AP/欲望数值的模组。不知道可不可以进行整合，辛苦了，非常感谢！

[AP欲望显示.txt](https://github.com/sakarie9/DOL-CHS-MODS/files/13218934/AP.txt)
![AP](https://github.com/sakarie9/DOL-CHS-MODS/assets/148609564/113893e3-445e-4b4d-acda-64df9f259187)

**Comment by sakarie9** [comment]
7d1d442

**Comment by HSSkyBoy** [comment]
@sakarie9 雖然我不知道為什麼，但這個模組似乎可以實現，不過為什麼我在v0.4.3.3-alpha2.0.0-1103㆗沒有看到這個模組的選項，莫⾮它和作弊或顯⽰HP的模組混合在⼀起了？

**Comment by sakarie9** [comment]
> @sakarie9 雖然我不知道為什麼，但這個模組似乎可以實現，不過為什麼我在v0.4.3.3-alpha2.0.0-1103㆗沒有看到這個模組的選項，莫⾮它和作弊或顯⽰HP的模組混合在⼀起了？

合并到HP显示里了
