### ISSUE TITLE
『HP顯示』是否應更名

### ISSUE THREAD

**Issue by HSSkyBoy** [sakarie9/DOL-CHS-MODS#14]
兩天前[Issues13](https://github.com/sakarie9/DOL-CHS-MODS/issues/13)提出了個增加AP欲望顯示的功能，也確實加入了（當初沒看到，抱歉），那麽HP顯示就不像之前一樣，單單顯示血量了，那麽，是否就意味著該改名了？

**Comment by sakarie9** [comment]
后续会改成HPAP之类的

**Comment by HSSkyBoy** [comment]
HAP(雾)
鴻蒙應用程序是吧～

我認為改名為『战⽃状态显⽰』更好，血氧值和魅惑值都是屬於戰鬥狀態的吧？

**Comment by sakarie9** [comment]
也好，缩写就写成 Combat Status Display - CSD 好了

**Comment by HSSkyBoy** [comment]
還好，這個挺行的(第一眼看成了COD:P
