### ISSUE TITLE
 关于作弊功能的功能请求

### ISSUE THREAD

**Issue by HSSkyBoy** [sakarie9/DOL-CHS-MODS#15]
在此处自带的作弊功能中，关于胡椒喷雾（防狼喷雾）能否增加两项功能？一个是增加防狼喷雾的数量上限，一个是增加防狼喷雾的数量

**Comment by sakarie9** [comment]
作弊界面为游戏内置，可直接使用作弊内的无限喷雾，或使用言灵增加喷雾数量
