### ISSUE TITLE
汉化BUG

### ISSUE THREAD

**Issue by Yu9188** [sakarie9/DOL-CHS-MODS#16]
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/90045451/3740d39d-bd1e-4a01-a75c-e6aef990461a)
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/90045451/a3664280-bd26-4fa4-9299-0a8a23a408c3)
内置的汉化包 有些部分没有汉化到 版本 DoL-0.4.3.3-chsmods-a2.2.1-besc-cheat-csd-1118.zip

**Comment by Yu9188** [comment]
用干净的版本下去导入汉化包是正常的

**Comment by sakarie9** [comment]
大概是cheat和csd直接修改了源文件的问题，下个版本将改为mod加载

**Comment by sakarie9** [comment]
暂时打开，等修复后再关闭

**Comment by sakarie9** [comment]
1120.1 已修复
