### ISSUE TITLE
加载Mod的时候，出现问题

### ISSUE THREAD

**Issue by chiasihee** [sakarie9/DOL-CHS-MODS#19]
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/27054780/ef17ead3-788c-455e-a0e0-36adf85ad37b)

它会出现以上的问题，已经下载你们提供的版本了还是有问题。Error: Error: bootJson文件 [boot.json] 无效

**Comment by sakarie9** [comment]
本仓库是整合包不是mod
