### ISSUE TITLE
使用模组加载器

### ISSUE THREAD

**Issue by linonetwo** [sakarie9/DOL-CHS-MODS#20]
下载了整合包尝试加载报错 Error: Error: bootJson文件 [boot.json] 无效 ，发现其实这里还没用上 https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.3.3-chs-alpha2.5.0 最新的模组加载器。

希望能提供能用模组加载器加载的版本。

**Comment by sakarie9** [comment]
本项目是整合包，作为本体游玩，并不是能加载进modloader的mod
