### ISSUE TITLE
一个小bug，虽然不影响使用但是挺奇怪的

### ISSUE THREAD

**Issue by Cansburg** [sakarie9/DOL-CHS-MODS#22]
解压的时候突然提示有重复的文件，看着提示找了找发现有两个重名图片？
路径为"./img/clothes/under_upper/leotard/"
应该是新整合的美化包有问题？找了汉化组发布的包和我手里的旧版BESC美化包没有这俩文件
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/50489292/7ca9141b-e015-4531-93b4-34165023d07b)

比起怎么解决更好奇怎么办到的.jpg

**Comment by sakarie9** [comment]
原版有 [hold_gray.PNG](https://gitgud.io/Vrelnir/degrees-of-lewdity/-/blob/master/img/clothes/under_upper/leotard/hold_gray.PNG)，但是美化包里是 hold_gray.png，在不区分大小写的 Windows 里解压大概就会提示重复文件

**Comment by Cansburg** [comment]
> 原版有 [hold_gray.PNG](https://gitgud.io/Vrelnir/degrees-of-lewdity/-/blob/master/img/clothes/under_upper/leotard/hold_gray.PNG)，但是美化包里是 hold_gray.png，在不区分大小写的 Windows 里解压大概就会提示重复文件

那解决方法应该是删掉原版，保留美化包的版本？

**Comment by sakarie9** [comment]
对，保留 `hold_gray.png`，`.PNG` 是错的

已经给原版提了issue了，等上游处理吧
