### ISSUE TITLE
想问有没有办法自己再加模组

### ISSUE THREAD

**Issue by Lauren0103** [sakarie9/DOL-CHS-MODS#3]
嘗試在整合版上加fire mod但发现图档和原版的有些分別
由於模组作者沒有在模组安裝器中提供汉化模组
所以想问问有没有办法或是工具可以加上这个模组

**Comment by sakarie9** [comment]
是在本整合上加入fire mod吗

因为汉化仓库似乎没有放出源码，很难做到直接在编译出的html文件里加入大型mod的代码，目前能做的也只是简单修改html或者添加一些覆盖源文件的美化

**Comment by Lauren0103** [comment]
是的，我想在整合上加入fire mod
但模组作者说他有少量改变程式码，加上图档和原版有出入
我不清楚能用什么办法或者能不能加入这个模组

**Comment by sakarie9** [comment]
大概不行，firemod基于22年11月的0.3.13.5，跟仓库里的0.4.2.6差太多了

真的想玩可以以firemod为底包手动往上打美化mod，但首先没有汉化，然后版本差太多美化包也不一定能用

**Comment by Lauren0103** [comment]
明白了
我再蹲蹲之後的更新
