### ISSUE TITLE
10/6版的小錯誤

### ISSUE THREAD

**Issue by zhigk** [sakarie9/DOL-CHS-MODS#4]
現在這個10/6最新版的新衣服或某些衣服有更新、然後還直接跟身體接不上、雖然可能是原版的問題但還是說一下

**Comment by zhigk** [comment]
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/54781313/2e62e6c2-f550-407c-8c25-b414e102205b)

**Comment by zhigk** [comment]
哦搞懂了、衣服是原版新加、然而美化身體沒更新

**Comment by sakarie9** [comment]
确实，新版本更新后美化没有覆盖到的地方都会有些错位，等美化更新吧

**Comment by sakarie9** [comment]
今天的BESC更新修复了一部分错位问题
