### ISSUE TITLE
分离社区美化包

### ISSUE THREAD

**Issue by HSSkyBoy** [sakarie9/DOL-CHS-MODS#5]
介紹中的BES有個『社區美化包』，不知能否單獨出來QQ 因為我並不喜歡它的美化 :(

**Comment by sakarie9** [comment]
已分离美化包

**Comment by sakarie9** [comment]
测试了一下目前BES有很严重的问题，暂时还是只能跟BESC已启用
![图片](https://github.com/sakarie9/DOL-CHS-MODS/assets/20642596/81da24ab-1d8e-4257-b3cf-120b378dfcfc)

**Comment by HSSkyBoy** [comment]
我個人是只喜歡用作弊加HP的，因為我並不喜歡Degrees of Lewdity Graphics模組
我的意思是指能否在作弊加HP這個功能上加上DCSC模組，而沒有DLG

**Comment by sakarie9** [comment]
DCSC基于DLG...不装社区美化就会错位

**Comment by HSSkyBoy** [comment]
可惜
