### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by Ark-Two** [sakarie9/DOL-CHS-MODS#6]
手机上已经安装了0.4.1.7版本的DOL CHS MODS,但是安装最新版的时候却显示版本冲突，即便卸载掉也无法安装
（还有0.4.2.7的汉化原版）
![QQ图片20231009083530](https://github.com/sakarie9/DOL-CHS-MODS/assets/72326210/83c88889-aeeb-4c23-844c-98c39722ea7d)
![QQ图片20231009083532](https://github.com/sakarie9/DOL-CHS-MODS/assets/72326210/eaff2692-4f53-4be5-8784-de2fa8e65189)

**Comment by sakarie9** [comment]
已修复

**Comment by HSSkyBoy** [comment]
apk證書是您自己的簽章，還是默認簽章？
如果是您自己的簽章，可否公開QQ

**Comment by sakarie9** [comment]
> apk證書是您自己的簽章，還是默認簽章？ 如果是您自己的簽章，可否公開(/ω＼) 畢竟有時候改apk沒同樣的證書，有點很麻煩

私钥，任何时候公开私钥都是很不安全的行为所以还是不公开了

mt管理器的改包和签名功能很方便可以考虑用用

**Comment by HSSkyBoy** [comment]
因為我沒root，所以沒安裝xp模塊
所以apk如果跟原apk簽章不一致的話，就得卸載重裝
這就會導致我的應用的cookie(或許吧)丟失，一些配置也沒了，很麻煩
