### ISSUE TITLE
Picture problem?

### ISSUE THREAD

**Issue by sakdd** [sakarie9/DOL-CHS-MODS#7]
dol-chs-a4.0.0-besc-wax-cheat-hp-1009.1
Picture problem?
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/86785456/d8368d90-2860-4ffb-9f8b-b48175ca6eb4)
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/86785456/bcb86edd-6c39-4a44-8d88-0147e1c460b6)

**Comment by sakarie9** [comment]
Breasts from wax are just too big to match the clothes, try other variants without wax. Or report the issue to wax repo, maybe the original author can fix it.

**Comment by sakarie9** [comment]
Seems fixed now

![图片](https://github.com/sakarie9/DOL-CHS-MODS/assets/20642596/b845af27-2dc2-4b27-8725-05a8b440311b)
