### ISSUE TITLE
Clothes are not in the correct position

### ISSUE THREAD

**Issue by ttayesset** [sakarie9/DOL-CHS-MODS#8]
Version: dol-chs-a4.0.0-besc-cheat-hp
Hope it will be fixed next time
There are some more, please take a look, I only listed some
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/121930520/90f54e67-cb8d-4cd0-9ef5-824de5a4f248)
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/121930520/cc840d5a-dce9-4fa4-857e-8e896a2fcd3a)
![image](https://github.com/sakarie9/DOL-CHS-MODS/assets/121930520/b861bf5e-a4f8-4646-9e37-33f5f47a93a9)

**Comment by sakarie9** [comment]
These are vanilla clothes and not redrawed by besc yet, please wait for besc to complete them, and i will catch up on updates once they are published.

**Comment by HSSkyBoy** [comment]
This is the Chinese Mods Area, can you speak Chinese? (Although I know what you say)
