### ISSUE TITLE
请求在下次 Releases 更新中添加一个新的组合

### ISSUE THREAD

**Issue by Meow0x7E** [sakarie9/DOL-CHS-MODS#9]
我在最新的 [Releases](https://github.com/sakarie9/DOL-CHS-MODS/releases/tag/v0.4.2.7-alpha4.0.0-1011) 中没有找到符合我预期的组合

我的想要的组合是 `BESC+HP+BJ+WAX`。但我没有在提供的版本选择中找到符合预期的组合。比较符合预期的是 [BESC+作弊+HP+BJ特写+WAX](https://github.com/sakarie9/DOL-CHS-MODS/releases/download/v0.4.2.7-alpha4.0.0-1011/dol-chs-a4.0.0-besc-wax-cheat-hp-sideviewbj-1011.zip) 但我并不希望有作弊菜单。因为作弊菜单就在手边，我觉得我忍不住不会去用:P

请在下次 Releases 更新中包含上述的组合，十分感谢！

**Comment by Huiqing998** [comment]
暂时应急的方法：
使用[VSC](https://code.visualstudio.com/download)等代码工具，CTRL+F搜索 `&lt;&lt;button 作弊&gt;&gt;` ,你能看到这两行代码：
```
&lt;&lt;if $dancing is 0 and $combat is 0 and $passage isnot &quot;Start2&quot;  or $debug is 1&gt;&gt;
&lt;&lt;button 作弊&gt;&gt;
```
在 `or $debug is 1&gt;&gt;` 前面添加 `and $cheatdisable is &quot;f&quot;` 即可
成品是这样子的：
```
&lt;&lt;if $dancing is 0 and $combat is 0 and $passage isnot &quot;Start2&quot; and $cheatdisable is &quot;f&quot; or $debug is 1&gt;&gt;
&lt;&lt;button 作弊&gt;&gt;
```

**Comment by sakarie9** [comment]
加上了，下次release会自动打包

**Comment by Meow0x7E** [comment]
感谢，已经玩上完美符合预期的DoL了！
![Screenshot_20231012_134635_org mozilla fenix](https://github.com/sakarie9/DOL-CHS-MODS/assets/133293581/7a5fb4b2-0255-4c5f-96e2-3205321aef6c)
![Screenshot_20231012_134524_com termux](https://github.com/sakarie9/DOL-CHS-MODS/assets/133293581/560a2983-836c-4421-afd4-0160e99b17a9)

**Comment by Meow0x7E** [comment]
有"作弊"和无"作弊"的版本，是否只是上面讲的那种临时解决方法提到的那行代码参数不同？

**Comment by sakarie9** [comment]
> 有"作弊"和无"作弊"的版本，是否只是上面讲的那种临时解决方法提到的那行代码参数不同？

一样的原理 https://github.com/sakarie9/DOL-CHS-MODS/blob/7af96a2d48c629aff599fd0fee556252fd497386/mod.sh#L199
